"""Interactive report services: reads, element settings, planning and generation.

cli/ and mcp/ call these (directly or via the re-exports in services.studio);
this module talks to the core client and raises only ServiceError subclasses.
"""

from __future__ import annotations

import threading
import time
from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

from notebooklm_tools.core import constants
from notebooklm_tools.core.errors import (
    ClientAuthenticationError,
    KickoffOutcomeUnknownError,
    ResourceExhaustedError,
    RPCError,
)
from notebooklm_tools.utils.config import get_default_language

from ._compat import TypedDict
from .errors import NotFoundError, ServiceError, ValidationError

if TYPE_CHECKING:
    from notebooklm_tools.core.client import NotebookLMClient

# kind -> public setting name -> (mapper, plain-Generate default name).
# Codes and defaults: spec §2.1 (captured live 2026-09-24).
ELEMENT_SETTINGS: dict[str, dict[str, tuple[constants.CodeMapper, str]]] = {
    "quiz": {
        "difficulty": (constants.FLASHCARD_DIFFICULTIES, "medium"),
        "question_amount": (constants.ELEMENT_AMOUNTS, "standard"),
    },
    "flashcards": {
        "difficulty": (constants.FLASHCARD_DIFFICULTIES, "medium"),
        "card_amount": (constants.ELEMENT_AMOUNTS, "fewer"),
    },
    "infographic": {
        "orientation": (constants.INFOGRAPHIC_ORIENTATIONS, "landscape"),
        "detail_level": (constants.INFOGRAPHIC_DETAILS, "standard"),
        "infographic_style": (constants.INFOGRAPHIC_STYLES, "auto_select"),
    },
    "slide_deck": {
        "slide_format": (constants.SLIDE_DECK_FORMATS, "detailed_deck"),
        "slide_length": (constants.REPORT_SLIDE_LENGTHS, "default"),
    },
    "audio": {"audio_format": (constants.AUDIO_FORMATS, "brief")},
    "video": {"video_format": (constants.REPORT_VIDEO_FORMATS, "cinematic")},
    "mind_map": {},
}

# Public setting name -> key understood by core.build_artifact_generation_payloads.
_PAYLOAD_KEYS = {
    "difficulty": "difficulty",
    "question_amount": "amount",
    "card_amount": "amount",
    "orientation": "orientation",
    "detail_level": "detail_level",
    "infographic_style": "infographic_style",
    "slide_format": "slide_format",
    "slide_length": "slide_length",
    "audio_format": "audio_format",
    "video_format": "video_format",
}

SUPPORTED_ELEMENT_KINDS = frozenset(ELEMENT_SETTINGS)


def describe_element_settings(kind: str) -> dict[str, dict[str, Any]]:
    """Allowed settings, values and defaults for one element kind."""
    schema = ELEMENT_SETTINGS.get(kind, {})
    return {
        name: {"values": sorted(mapper.names, key=mapper.get_code), "default": default}
        for name, (mapper, default) in schema.items()
    }


def resolve_element_settings(kind: str, settings: Mapping[str, Any] | None) -> dict[str, int]:
    """Validate public setting names/values for ``kind`` and return payload codes."""
    if kind not in SUPPORTED_ELEMENT_KINDS:
        raise ValidationError(f"Element type '{kind}' cannot be generated by this tool.")
    schema = ELEMENT_SETTINGS[kind]
    resolved: dict[str, int] = {}
    for raw_name, raw_value in (settings or {}).items():
        name = str(raw_name).strip().lower()
        if name not in schema:
            allowed = ", ".join(schema) or "none"
            raise ValidationError(
                f"Setting '{raw_name}' does not apply to {kind} elements. Allowed: {allowed}."
            )
        mapper, _ = schema[name]
        value = str(raw_value).strip().lower()
        try:
            resolved[_PAYLOAD_KEYS[name]] = mapper.get_code(value)
        except ValueError:
            raise ValidationError(
                f"Invalid {name} '{raw_value}' for {kind}. "
                f"Allowed: {', '.join(sorted(mapper.names, key=mapper.get_code))}."
            ) from None
    return resolved


class ReportElementInfo(TypedDict, total=False):
    """One embedded element of an interactive report."""

    element_id: str
    type: str
    title: str
    element_status: str
    steering_prompt: str | None
    description: str | None
    section: dict[str, str] | None
    settings: dict[str, dict[str, Any]]
    content: dict[str, Any] | None
    content_note: str | None


class ReportInfo(TypedDict, total=False):
    """Interactive report contents for agents."""

    artifact_id: str
    title: str
    status: str
    parse_status: str
    prompt: str | None
    language: str | None
    markdown: str | None
    source_ids: list[str]
    elements: list[ReportElementInfo]


class ReportElementResult(TypedDict):
    """Result of starting generation for one embedded element."""

    report_id: str
    element_id: str
    title: str | None
    outcome: str
    element_status: str | None
    message: str


def _require_interactive_report(
    client: NotebookLMClient,
    notebook_id: str,
    artifact_id: str,
) -> dict[str, Any]:
    """Fetch an artifact and validate that it is an interactive report."""
    info = client.describe_artifact(notebook_id, artifact_id)
    if info is None:
        raise NotFoundError(
            f"Artifact {artifact_id} not found in notebook {notebook_id}.",
            user_message=f"Artifact {artifact_id} was not found.",
        )
    if info.get("type") != "interactive_report":
        raise ValidationError(
            f"Artifact {artifact_id} is a '{info.get('type', 'unknown')}', "
            "not an interactive report.",
        )
    return info


def _element_info(
    client: NotebookLMClient,
    notebook_id: str,
    element_id: str,
    section: dict[str, str] | None = None,
) -> ReportElementInfo:
    """Fetch one embedded element and return its public description."""
    info = client.describe_artifact(notebook_id, element_id)
    if info is None:
        return ReportElementInfo(
            element_id=element_id,
            type="unknown",
            title="",
            element_status="missing",
            steering_prompt=None,
            description=None,
            section=section,
            settings={},
        )
    kind = str(info.get("type") or "unknown")
    return ReportElementInfo(
        element_id=element_id,
        type=kind if kind in SUPPORTED_ELEMENT_KINDS else "unsupported",
        title=str(info.get("title") or ""),
        element_status=str(info.get("status") or "unknown"),
        steering_prompt=info.get("steering_prompt"),
        description=info.get("description"),
        section=section,
        settings=describe_element_settings(kind),
    )


def _report_elements(
    client: NotebookLMClient, notebook_id: str, report: dict[str, Any]
) -> list[ReportElementInfo]:
    sections = report.get("report_sections") or {}
    return [
        _element_info(client, notebook_id, ref["element_id"], sections.get(ref["element_id"]))
        for ref in (report.get("report_elements") or [])
    ]


def get_report(
    client: NotebookLMClient,
    notebook_id: str,
    artifact_id: str,
) -> ReportInfo:
    """Read an interactive report: markdown, prompt, language and elements.

    Returns:
        ReportInfo with the rendered markdown and embedded element metadata

    Raises:
        NotFoundError: If the artifact does not exist
        ValidationError: If the artifact is not an interactive report
        ServiceError: If the artifact could not be fetched
    """
    try:
        info = _require_interactive_report(client, notebook_id, artifact_id)
    except (NotFoundError, ValidationError):
        raise
    except Exception as e:
        raise ServiceError(
            f"Failed to fetch report {artifact_id}: {e}",
            user_message="Could not fetch the interactive report.",
        ) from e

    elements = _report_elements(client, notebook_id, info)

    return ReportInfo(
        artifact_id=str(info.get("artifact_id") or artifact_id),
        title=str(info.get("title") or ""),
        status=str(info.get("status") or "unknown"),
        parse_status=str(info.get("parse_status") or "pending"),
        prompt=info.get("report_prompt"),
        language=info.get("report_language"),
        markdown=info.get("report_content"),
        source_ids=[sid for sid in (info.get("source_ids") or []) if isinstance(sid, str)],
        elements=elements,
    )


REVIEW_LABEL = "Checked against the plan and the report section, not against the original sources."
_TERMINAL = frozenset({"completed", "failed", "suggested", "missing", "unsupported"})
_REVIEWABLE = frozenset({"quiz", "flashcards", "mind_map"})


class ElementListResult(TypedDict):
    elements: list[ReportElementInfo]
    timed_out: bool
    review_label: str | None


def get_element_content(
    client: NotebookLMClient, notebook_id: str, element: ReportElementInfo
) -> dict[str, Any] | None:
    """Structured content of a completed quiz, flashcard deck or mind map."""
    data = client.get_interactive_app_data(notebook_id, element["element_id"])
    if not data:
        return None
    kind = element.get("type")
    if kind == "quiz":
        return {"questions": data.get("quiz", [])}
    if kind == "flashcards":
        return {
            "cards": [
                {"front": c.get("f", ""), "back": c.get("b", "")}
                for c in data.get("flashcards", [])
            ]
        }
    return data  # mind map tree: {"name": ..., "children": [...]}


def list_report_elements(
    client: NotebookLMClient,
    notebook_id: str,
    artifact_id: str,
    *,
    wait_for: list[str] | None = None,
    timeout: float = 600.0,
    poll_interval: float = 15.0,
    include_content: bool = False,
    _sleep=time.sleep,
    _monotonic=time.monotonic,
) -> ElementListResult:
    """List report elements; optionally wait on explicit ids and inline content."""
    report = _require_interactive_report(client, notebook_id, artifact_id)
    deadline = _monotonic() + timeout
    timed_out = False
    while True:
        elements = _report_elements(client, notebook_id, report)
        if not wait_for:
            break
        by_id = {e["element_id"]: e for e in elements}
        pending = [
            eid
            for eid in wait_for
            if eid in by_id and by_id[eid].get("element_status") not in _TERMINAL
        ]
        if not pending:
            break
        if _monotonic() >= deadline:
            timed_out = True
            break
        _sleep(poll_interval)

    if wait_for:
        known = {e["element_id"] for e in elements}
        elements.extend(
            ReportElementInfo(element_id=eid, element_status="missing")
            for eid in wait_for
            if eid not in known
        )

    if include_content:
        for element in elements:
            if element.get("element_status") != "completed":
                continue
            if element.get("type") in _REVIEWABLE:
                try:
                    element["content"] = get_element_content(client, notebook_id, element)
                except Exception as e:  # noqa: BLE001 - one element must not sink the listing
                    element["content"] = None
                    element["content_note"] = f"content unavailable: {e}"
            else:
                element["content_note"] = "not reviewable in v1"

    return ElementListResult(
        elements=elements,
        timed_out=timed_out,
        review_label=REVIEW_LABEL if include_content else None,
    )


MAX_PLAN_ITEMS = 20
MAX_PROMPT_CHARS = 4000
_PLAN_KEYS = frozenset({"element_id", "steering_prompt", "settings"})


class ElementPlanItem(TypedDict, total=False):
    element_id: str
    steering_prompt: str | None
    settings: dict[str, str]


@dataclass
class PreparedElement:
    element_id: str
    type: str
    title: str
    prompt: str
    settings: dict[str, int] = field(default_factory=dict)
    settings_named: dict[str, str] = field(default_factory=dict)


@dataclass
class PreparedPlan:
    report_id: str
    source_ids: list[str]
    language: str
    elements: list[PreparedElement]


def parse_element_plan(raw: Any) -> list[ElementPlanItem]:
    """Strictly parse an element plan (MCP argument or CLI plan file content)."""
    if not isinstance(raw, list):
        raise ValidationError("An element plan must be a list of items.")
    if not 1 <= len(raw) <= MAX_PLAN_ITEMS:
        raise ValidationError(f"An element plan must have 1 to {MAX_PLAN_ITEMS} items.")
    items: list[ElementPlanItem] = []
    for index, entry in enumerate(raw, 1):
        if not isinstance(entry, dict):
            raise ValidationError(f"Plan item {index} must be an object.")
        unknown = set(entry) - _PLAN_KEYS
        if unknown:
            raise ValidationError(
                f"Plan item {index} has unknown keys: {', '.join(sorted(unknown))}."
            )
        element_id = entry.get("element_id")
        if not isinstance(element_id, str) or not element_id.strip():
            raise ValidationError(f"Plan item {index} needs an element_id.")
        prompt = entry.get("steering_prompt")
        if prompt is not None and not isinstance(prompt, str):
            raise ValidationError(f"Plan item {index}: steering_prompt must be text.")
        if prompt is not None and len(prompt) > MAX_PROMPT_CHARS:
            raise ValidationError(
                f"Plan item {index}: steering_prompt is over {MAX_PROMPT_CHARS} characters."
            )
        settings = entry.get("settings") or {}
        if not isinstance(settings, dict) or not all(
            isinstance(k, str) and isinstance(v, str) for k, v in settings.items()
        ):
            raise ValidationError(f"Plan item {index}: settings must map names to text values.")
        items.append(
            ElementPlanItem(
                element_id=element_id.strip(), steering_prompt=prompt, settings=settings
            )
        )
    return items


def prepare_element_plan(
    client: NotebookLMClient,
    notebook_id: str,
    report_id: str,
    items: list[ElementPlanItem],
    language: str | None = None,
) -> PreparedPlan:
    """Validate a plan completely using reads only. Nothing is sent to Google."""
    report = _require_interactive_report(client, notebook_id, report_id)
    if report.get("status") != "completed" or report.get("parse_status") == "pending":
        raise ValidationError(f"Report {report_id} is not ready yet; wait until it is completed.")
    if report.get("parse_status") == "unrecognized":
        raise ValidationError(
            f"Report {report_id} has a structure this tool does not recognize; "
            "generate elements from the report view instead."
        )
    source_ids = [s for s in (report.get("source_ids") or []) if isinstance(s, str)]
    if not source_ids:
        raise ValidationError(
            f"Could not resolve the sources of report {report_id}; refusing to generate "
            "elements without them (they would otherwise use every notebook source)."
        )
    by_id = {e["element_id"]: e for e in _report_elements(client, notebook_id, report)}

    seen: set[str] = set()
    prepared: list[PreparedElement] = []
    for item in items:
        eid = item["element_id"]
        if eid in seen:
            raise ValidationError(f"Element {eid} appears more than once in the plan.")
        seen.add(eid)
        element = by_id.get(eid)
        if element is None:
            raise NotFoundError(
                f"Element {eid} is not embedded in report {report_id}.",
                user_message=f"Element {eid} is not part of this report.",
            )
        status = element.get("element_status")
        if status != "suggested":
            raise ValidationError(
                f"Element {eid} is {status}; only suggested elements can be generated "
                "(it has already been started or cannot be read)."
            )
        kind = element.get("type") or "unknown"
        named = {
            k.strip().lower(): v.strip().lower() for k, v in (item.get("settings") or {}).items()
        }
        codes = resolve_element_settings(kind, named)
        prompt = item.get("steering_prompt")
        if prompt is None:
            prompt = element.get("steering_prompt") or element.get("description") or ""
        prepared.append(
            PreparedElement(
                element_id=eid,
                type=kind,
                title=str(element.get("title") or ""),
                prompt=prompt,
                settings=codes,
                settings_named=named,
            )
        )
    return PreparedPlan(
        report_id=report_id,
        source_ids=source_ids,
        language=language or report.get("report_language") or get_default_language(),
        elements=prepared,
    )


_LOCKS_GUARD = threading.Lock()
_ELEMENT_LOCKS: dict[str, threading.Lock] = {}


def _element_lock(element_id: str) -> threading.Lock:
    """Per-element lock so overlapping calls in this process cannot double-start.

    Cross-process/cross-client races (another machine, the web UI) are not
    covered; see the spec's documented limitation.
    """
    with _LOCKS_GUARD:
        return _ELEMENT_LOCKS.setdefault(element_id, threading.Lock())


class ElementOutcome(TypedDict):
    element_id: str
    title: str
    outcome: str
    element_status: str | None
    error: str | None
    error_category: str | None


class BatchResult(TypedDict):
    report_id: str
    results: list[ElementOutcome]
    counts: dict[str, int]
    stopped_reason: str | None


def _outcome(
    el: PreparedElement, outcome: str, status=None, error=None, category=None
) -> ElementOutcome:
    return ElementOutcome(
        element_id=el.element_id,
        title=el.title,
        outcome=outcome,
        element_status=status,
        error=error,
        error_category=category,
    )


def _reconcile(client, notebook_id, element_id, reads, interval, sleep) -> str | None:
    """Re-read status after an ambiguous kickoff. Never re-sends."""
    for attempt in range(reads):
        if attempt:
            sleep(interval)
        info = client.describe_artifact(notebook_id, element_id)
        status = (info or {}).get("status")
        if status and status != "suggested":
            return status
    return None


def execute_element_plan(
    client: NotebookLMClient,
    notebook_id: str,
    plan: PreparedPlan,
    *,
    reconcile_reads: int = 3,
    reconcile_interval: float = 5.0,
    _sleep=time.sleep,
) -> BatchResult:
    """Start every element of a validated plan. See spec §4.5 for the rules."""
    results: list[ElementOutcome] = []
    stopped: str | None = None
    for el in plan.elements:
        if stopped:
            results.append(_outcome(el, "not_started", error=f"Stopped after {stopped} failure."))
            continue
        lock = _element_lock(el.element_id)
        if not lock.acquire(blocking=False):
            results.append(
                _outcome(el, "failed", error="Generation already in progress in this process.")
            )
            continue
        try:
            # Re-check under the lock: another call may have started this element
            # after the plan was validated. Never start a non-suggested element.
            current = client.describe_artifact(notebook_id, el.element_id)
            current_status = (current or {}).get("status")
            if current_status != "suggested":
                results.append(
                    _outcome(
                        el,
                        "failed",
                        status=current_status,
                        error=(
                            f"Element is {current_status or 'missing'}; it was started or "
                            "changed after the plan was validated. Not re-sent."
                        ),
                        category="not_suggested",
                    )
                )
                continue

            started = client.start_artifact_generation(
                notebook_id,
                el.element_id,
                steering_prompt=el.prompt,
                language=plan.language,
                source_ids=plan.source_ids,
                settings=el.settings,
            )
            results.append(_outcome(el, "started", status=started.get("status")))
        except ResourceExhaustedError as e:
            stopped = "quota"
            results.append(_outcome(el, "failed", error=str(e), category="quota"))
        except ClientAuthenticationError as e:
            stopped = "auth"
            results.append(_outcome(el, "failed", error=str(e), category="auth"))
        except KickoffOutcomeUnknownError as e:
            status = _reconcile(
                client, notebook_id, el.element_id, reconcile_reads, reconcile_interval, _sleep
            )
            if status:
                results.append(_outcome(el, "started", status=status))
            else:
                results.append(
                    _outcome(
                        el,
                        "unknown",
                        error=f"{e} Not re-sent; check status later.",
                        category="unknown_outcome",
                    )
                )
        except RPCError as e:
            results.append(_outcome(el, "failed", error=str(e), category=f"rpc_{e.error_code}"))
        except Exception as e:  # noqa: BLE001 - one item must not sink the batch
            results.append(_outcome(el, "failed", error=str(e), category="error"))
        finally:
            lock.release()

    counts = {k: 0 for k in ("started", "failed", "unknown", "not_started")}
    for r in results:
        counts[r["outcome"]] += 1
    return BatchResult(
        report_id=plan.report_id, results=results, counts=counts, stopped_reason=stopped
    )


def generate_report_elements(
    client: NotebookLMClient,
    notebook_id: str,
    report_id: str,
    items: list[ElementPlanItem],
    *,
    language: str | None = None,
    **execute_kwargs: Any,
) -> BatchResult:
    """Validate a plan (reads only), then start its elements safely."""
    plan = prepare_element_plan(client, notebook_id, report_id, items, language)
    return execute_element_plan(client, notebook_id, plan, **execute_kwargs)


def generate_report_element(
    client: NotebookLMClient,
    notebook_id: str,
    artifact_id: str,
    *,
    element_id: str | None = None,
    element_type: str | None = None,
    steering_prompt: str | None = None,
    language: str | None = None,
    settings: Mapping[str, str] | None = None,
) -> ReportElementResult:
    """Generate one element through the same safe path as batch generation."""
    report = _require_interactive_report(client, notebook_id, artifact_id)
    elements = _report_elements(client, notebook_id, report)
    if not elements:
        raise ServiceError(
            "Interactive report has no embedded elements.",
            user_message="Report has no embedded elements to generate.",
        )
    if element_id:
        target_id = element_id
    elif element_type:
        wanted = element_type.strip().lower()
        matches = [e for e in elements if (e.get("type") or "").lower() == wanted]
        if not matches:
            available = ", ".join(sorted({(e.get("type") or "unknown") for e in elements}))
            raise NotFoundError(
                f"No embedded element of type '{element_type}' in report {artifact_id}.",
                user_message=f"Available element types: {available}.",
            )
        target_id = next(
            (e for e in matches if e.get("element_status") == "suggested"), matches[0]
        )["element_id"]
    else:
        raise ValidationError("Provide element_id or element_type to select an element.")

    item = ElementPlanItem(element_id=target_id, settings=dict(settings or {}))
    if steering_prompt is not None:
        item["steering_prompt"] = steering_prompt
    batch = generate_report_elements(client, notebook_id, artifact_id, [item], language=language)
    outcome = batch["results"][0]
    if outcome["outcome"] in ("failed", "not_started"):
        raise ServiceError(
            f"Failed to start element generation: {outcome['error']}",
            user_message=f"Could not start generating the element: {outcome['error']}",
            category=outcome["error_category"],
        )
    return ReportElementResult(
        report_id=artifact_id,
        element_id=outcome["element_id"],
        title=outcome["title"],
        outcome=outcome["outcome"],
        element_status=outcome["element_status"],
        message=(
            "Element generation started."
            if outcome["outcome"] == "started"
            else "Kickoff outcome unknown; not re-sent. Check the element status before retrying."
        ),
    )
